---
- name: Add postgresql repo key
  apt_key: id=ACCC4CF8 url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present
  tags: postgresql

- name: Add postgresql repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
  tags: postgresql

- name: Install postgresql
  apt: name=$item state=installed
  with_items:
    - python-psycopg2
    - postgresql-9.2
  tags: postgresql

- name: Start PostgreSQL and enable at boot
  service: name=postgresql enabled=yes state=started
  tags: postgresql

- name: Ensure PostgreSQL is listening on all localhost
  sudo_user: postgres
  lineinfile: dest=/etc/postgresql/9.2/main/postgresql.conf
    regexp='^#?listen_addresses\s*='
    line="listen_addresses = '127.0.0.1'"
    state=present
  notify: restart postgresql
  tags: postgresql

- name: Ensure PostgreSQL is listening on all localhost
  sudo_user: postgres
  lineinfile: dest=/etc/postgresql/9.2/main/pg_hba.conf
             regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
             line='host all all 127.0.0.1/32 md5'
             insertbefore=BOF
  notify: restart postgresql
  tags: postgresql

- name: Reload PostgreSQL
  service: name=postgresql state=reloaded
  tags: postgresql