---
- name: Add postgresql repo key
  apt_key: id=ACCC4CF8 url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Add postgresql repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'

- name: Install postgresql
  apt: name={{ item }} state=installed update-cache=yes
  with_items:
    - postgresql-client-9.4
    - libpq-dev
  
# - name: Start postgresql container
#   docker: image=postgres name=postgres ports=5432:5432