---
- name: Create users
  sudo_user: postgres
  postgresql_user: user={{ item }} password={{ lookup('password', '../../../secrets/db/' + item + ' encrypt=sha256_crypt') }} role_attr_flags=CREATEDB,NOSUPERUSER
  with_items: postgresql.users

- name: Create databases
  sudo_user: postgres
  postgresql_db: db={{ item }} owner={{ item }}
  with_items: postgresql.users

- name: Grant rights
  sudo_user: postgres
  postgresql_privs: db={{ item }} roles={{ item }} privs=ALL type=database
  with_items: postgresql.users