---
# - name: create db
#   mysql_db: name={{ dev_skyltmax_db }} state=present encoding=utf8 login_user=root login_password={{ mariadb_pw }} login_host=127.0.0.1

# - name: create db user
#   mysql_user: name={{ dev_skyltmax_db_user }} password={{ dev_skyltmax_db_pass }} host={{ ansible_docker0.ipv4.address }} priv={{ dev_skyltmax_db }}.*:ALL state=present login_user=root login_password={{ mariadb_pw }} login_host=127.0.0.1

# - name: install database.yml
#   template: src=database.yml.j2 dest={{ dev_skyltmax_dir }}/config/database.yml
#   notify: restart skyltmax

# - name: install skyltmax service
#   template: src=skyltmax.service.j2 dest=/etc/systemd/system/skyltmax.service
#   notify: restart skyltmax

# - name: enable service
#   service: name=skyltmax state=started enabled=yes

# - name: Write site
#   template: src=nginx.j2 dest=/etc/nginx/sites-available/01-{{ dev_skyltmax_domain }}.conf
#   notify: reload nginx

# - name: Link site
#   file: src=/etc/nginx/sites-available/01-{{ dev_skyltmax_domain }}.conf dest=/etc/nginx/sites-enabled/01-{{ dev_skyltmax_domain }}.conf state=link
#   notify: reload nginx

# - name: Generate SSL cert
#   command: "{{ le_cmd }} -d {{ dev_skyltmax_domain }}"
