---
- name: Add deploy user
  user: name=deploy generate_ssh_key=yes ssh_key_bits=2048 ssh_key_comment={{ 'deploy@' + ansible_fqdn }}

- name: Copy sudoers file
  copy: src=sudo dest=/etc/sudoers.d/deploy owner=root mode=0400