---
- name: Add repo key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add repo
  apt_repository: repo='deb https://repos.influxdata.com/debian jessie stable'

- name: Install packages
  apt: name=influxdb update_cache=yes state=installed cache_valid_time=86400
  notify: restart influxdb

- name: copy ufw conf
  template: src=ufw.j2 dest=/etc/ufw/applications.d/influxdb owner=root group=root mode=0644
