---
- name: Install php-fpm and deps
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - graphicsmagick
    - graphicsmagick-imagemagick-compat
    - php-xml-parser
    - php-pear
    - php7.0-fpm
    - php7.0-dev
    - php7.0-enchant
    - php7.0-intl
    - php7.0-gd
    - php7.0-sqlite3
    - php7.0-curl
    - php7.0-cli
    - php7.0-json

# - name: Disable default pool
#   command: mv /etc/php5/fpm/pool.d/www.conf /etc/php5/fpm/pool.d/www.disabled creates=/etc/php5/fpm/pool.d/www.disabled
#   notify: restart php-fpm

- name: Disable FastCGI path info fix
  lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^;?cgi.fix_pathinfo' line='cgi.fix_pathinfo = 0;'
  notify: restart php-fpm

# - name: Increase APC memory segments to 8 (* 32 MB = 256 MB)
#   lineinfile: dest=/etc/php5/fpm/conf.d/apc.ini regexp='^;?apc.shm_segments' line='apc.shm_segments = 8;'
#   when: ansible_distribution_release == "precise"
#   notify: restart php-fpm

- name: Ensure php-fpm is started
  service: name=php7.0-fpm state=started
