---
- hosts: cheetah
  become: true
  roles:
    - common
    - newrelic
    - ruby
    - nginx
    - le
    - docker
    - php-fpm
    - moe
    - plex
    - couchpotato
    - sabnzbd
    - sonarr
    - deluge
    - jackett
    - java
    - plexpy
    - netdata
    - ipv6
