---
# - name: install bind
#   apt: name=bind9 update_cache=yes state=latest cache_valid_time=86400

- name: create directory
  file: path={{ gamecache_path }} owner=www-data group=www-data mode=2775 state=directory

- name: Write site
  template: src=nginx.j2 dest=/etc/nginx/sites-available/01-gamecache.conf
  notify: reload nginx

- name: Link site
  file: src=/etc/nginx/sites-available/01-gamecache.conf dest=/etc/nginx/sites-enabled/01-gamecache.conf state=link
  notify: reload nginx

# - name: create directory
#   file: path=/etc/bind/gamecache owner=root group=bind state=directory

# - name: Write bind config
#   template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local group=bind
#   notify: restart bind

# - name: Write bind config
#   template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options group=bind
#   notify: restart bind

# - name: Write bind config
#   template: src=gamecache.conf.j2 dest=/etc/bind/gamecache.conf group=bind
#   notify: restart bind

# - name: Write bind config
#   template: src=db.content_.steampowered.com.j2 dest=/etc/bind/gamecache/db.content_.steampowered.com group=bind
#   notify: restart bind

# - name: Write bind config
#   template: src=db.steamcontent.com.j2 dest=/etc/bind/gamecache/db.steamcontent.com group=bind
#   notify: restart bind

# - name: Write bind config
#   template: src=db.cs.steampowered.com.j2 dest=/etc/bind/gamecache/db.cs.steampowered.com group=bind
#   notify: restart bind

# - name: firewall allow bind
#   command: ufw allow bind9

# - name: start bind service
#   service: name=bind9 state=started enabled=yes
