---
nginx_version: 1.11.10
nginx_file: nginx-{{ nginx_version }}.zip
nginx_url: http://nginx.org/download/{{ nginx_file }}

nginx_win_dir: C:/nginx
nginx_win_log_dir: C:/nginx/logs
nginx_win_pid: C:/nginx/logs/nginx.pid


nginx_user: www-data
nginx_pid: /var/run/nginx.pid
nginx_dir: /etc/nginx
nginx_log_dir: /var/log/nginx
nginx_worker_connections: 4096
nginx_multi_accept: true
nginx_event: epoll
nginx_enable_access_log: true
nginx_sendfile: "on"
nginx_keepalive_timeout: 65
nginx_server_names_hash_bucket_size: 64
nginx_types_hash_max_size: 2048
nginx_types_hash_bucket_size: 64
nginx_proxy_read_timeout: 86400s # 1 day
nginx_client_max_body_size: 100m
nginx_gzip: "on"
nginx_gzip_http_version: "1.0"
nginx_gzip_comp_level: "2"
nginx_gzip_proxied: any
nginx_gzip_vary: "off"
nginx_gzip_types:
  - "text/plain"
  - "text/css"
  - "application/x-javascript"
  - "text/xml"
  - "application/atom+xml"
  - "application/xml"
  - "application/xml+rss"
  - "text/javascript"
  - "application/javascript"
  - "application/json"
