---
- name: download
  get_url: url={{ le_url }} dest={{ le_dest }}

- name: ensure correct mode
  file: path={{ le_dest }} mode=o+rx

- name: renewal cron
  cron: name="LE renew" minute="0" hour="5" weekday="0" job="{{ le_dest }} renew --post-hook \"{{ le_hook_root }}/renew.sh\" > /var/log/certbot.log 2>&1"

- name: Create LE directory
  file: path={{ le_webroot }} owner=www-data group=www-data mode=775 state=directory

- name: Create LE hooks directory
  file: path={{ le_hook_root }} state=directory

- name: Create LE hooks directory
  file: path={{ le_hook_root }}/scripts state=directory

- name: create renew script
  template: src=renew.sh.j2 dest={{ le_hook_root }}/renew.sh mode=755
