---
rtorrent_user: rtorrent
rtorrent_data_dir: /var/lib/rtorrent
rtorrent_download_dir: "/var/media/download/rtorrent"
rtorrent_session_dir: "{{ rtorrent_data_dir }}/session"
rtorrent_watch_dir: "{{ rtorrent_data_dir }}/watch"
rtorrent_port: 49164
rtorrent_dht_port: 6881
rtorrent_scgi_host: 127.0.0.1
rtorrent_scgi_port: 5000
rtorrent_umask: "002"
rtorrent_service_enable: yes
rtorrent_pid_file: /var/run/rtorrent.pid
rtorrent_log_file: /var/log/rtorrent.log
rtorrent_screen_name: rtorrent

rtorrent_install_rutorrent: yes
rtorrent_install_rutorrent_plugins: yes
rtorrent_rutorrent_version: ac2db1536302bdc5b27aff6b15d54b0e9837fa59
rtorrent_rutorrent_archive: ruTorrent-{{ rtorrent_rutorrent_version }}.zip
rtorrent_rutorrent_url: https://github.com/Novik/ruTorrent/archive/{{rtorrent_rutorrent_version}}.zip
rtorrent_rutorrent_install_path: /var/www/rutorrent
rtorrent_rutorrent_autotools_interval: 300

rtorrent_rutorrent_domain: rt.kris.moe
rtorrent_rutorrent_ssl_cert: /etc/ssl/certs/{{ rtorrent_rutorrent_domain }}.pem
rtorrent_rutorrent_ssl_key: /etc/ssl/private/{{ rtorrent_rutorrent_domain }}.key

# rtorrent_rutorrent_user:
# rtorrent_rutorrent_password:
