---
- name: create user
  user: name={{ radarr_user }} home={{ radarr_data_dir }} createhome=no system=yes shell=/bin/bash

- name: create directories
  file: path={{ item.path }} owner={{ radarr_user }} group={{ radarr_user }} mode={{ item.mode|default("755") }} state=directory
  with_items:
    - path: "{{ radarr_data_dir }}"
    - path: "{{ radarr_config_dir }}"

- name: delete directory
  file: path={{ radarr_install_dir }} state=absent

- name: download
  get_url: url={{ radarr_release_url }} dest=/tmp/{{ radarr_archive }}

- name: unpack archive
  unarchive: >
    src=/tmp/{{ radarr_archive }} dest=/opt copy=no
    creates={{ radarr_install_dir }}/Radarr.exe
  notify: restart radarr

- name: fix permissions
  file: path={{ radarr_install_dir }} owner={{ radarr_user }} group={{ radarr_user }} recurse=yes

- name: install service
  template: src=service.j2 dest=/etc/systemd/system/radarr.service mode=644
  notify: restart radarr

- name: enable service
  service: name=radarr state=started enabled=yes

- name: Write site
  template: src=nginx.j2 dest=/etc/nginx/sites-available/01-{{ radarr_domain }}.conf
  notify: reload nginx

- name: Link site
  file: src=/etc/nginx/sites-available/01-{{ radarr_domain }}.conf dest=/etc/nginx/sites-enabled/01-{{ radarr_domain }}.conf state=link
  notify: reload nginx

- name: Generate SSL cert
  command: "{{ le_cmd }} -d {{ radarr_domain }}"
