---
- name: Add mariadb repo key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xcbcb082a1bb943db state=present

- name: Add mariadb repo
  apt_repository: repo='deb http://mirror.netcologne.de/mariadb/repo/10.0/ubuntu trusty main'

- name: Install mariadb
  apt: name={{item}} state=installed update-cache=yes
  with_items:
    - mariadb-client
    - libmariadbclient-dev
    - python-mysqldb

- name: Start mariadb container
  docker:
    image: mariadb
    name: mariadb
    ports: 3606:3306
    volumes: /data/mysql:/var/lib/mysql
    env:
      MYSQL_ROOT_PASSWORD: docker