---
- name: Add mariadb repo key
  apt_key: keyserver=keyserver.ubuntu.com id=0xF1656F24C74CD1D8 state=present

- name: Add mariadb repo
  apt_repository: repo='deb [arch=amd64,i386,ppc64el] http://ftp.eenet.ee/pub/mariadb/repo/10.1/ubuntu xenial main'

- name: Install mariadb
  apt: name={{item}} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - mariadb-client
    - libmariadbclient-dev
    - python-mysqldb

- name: create db directory
  file: path={{ mariadb_data }} mode=770 state=directory

- name: create config directory
  file: path={{ mariadb_config }} mode=775 state=directory

- name: create configuration
  template: src=perf.cnf.j2 dest={{ mariadb_config }}/perf.cnf.j2

- name: start mariadb
  docker:
    name: mariadb
    image: mariadb:latest
    state: started
    pull: missing
    restart_policy: always
    ports:
    - 3306:3306
    volumes:
    - "{{ mariadb_data }}:/var/lib/mysql"
    - "{{ mariadb_config }}:/etc/mysql/conf.d"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mariadb_pw }}"
