---
- name: Install OpenVPN and dependencies from apt
  apt: pkg=$item state=installed
  with_items:
    - openvpn
    - udev
    - dnsmasq

- name: Copy setup scripts into place
  command: cp -R /usr/share/doc/openvpn/examples/easy-rsa/ /etc/openvpn

- name: Put easy-rsa parameter settings in place
  template: src=etc_openvpn_easy-rsa_2.0_vars.j2 dest=/etc/openvpn/easy-rsa/2.0/vars mode=0755

###### manually for each client:
# . /etc/openvpn/easy-rsa/2.0/build-key $client_name
#####

- name: Copy genkeys.sh
  copy: src=genkeys.sh dest=/etc/openvpn/easy-rsa/2.0/genkeys.sh mode=0755

- name: Generate server keys
  command: sh /etc/openvpn/easy-rsa/2.0/genkeys.sh  creates=/etc/openvpn/easy-rsa/2.0/keys/ca.crt

- name: Copy certificates and key files into place
  command: cp /etc/openvpn/easy-rsa/2.0/keys/$item /etc/openvpn creates=/etc/openvpn/$item
  with_items:
    - ca.crt
    - ca.key
    - dh1024.pem
    - "{{vpn.cn}}.crt"
    - "{{vpn.cn}}.key"

- name: Copy rc.local with firewall and dnsmasq rules into place
  copy: src=etc_rc.local dest=/etc/rc.local

- name: Enable IPv4 traffic forwarding
  lineinfile: dest=/etc/sysctl.conf regexp="^net.ipv4.ip_forward" line="net.ipv4.ip_forward=1"
- command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Allow OpenVPN through firewall
  command: $item
  with_items:
    - iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
    - iptables -A FORWARD -s 10.8.0.0/24 -j ACCEPT
    - iptables -A FORWARD -j REJECT
    - iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE

- name: Copy OpenVPN configuration file into place
  template: src=etc_openvpn_server.conf.j2 dest=/etc/openvpn/server.conf
  notify: restart openvpn

- name: Copy dnsmasq configuration file into place
  copy: src=etc_dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq
