---
- name: Make sure gome dir exists
  file: path=/home/deploy/gome recurse=yes state=directory owner=deploy group=deploy mode=0644

- name: Download gome
  get_url: url=https://github.com/krisrang/gome/releases/download/v0.1/gome dest=/home/deploy/gome/gome
  notify: restart gome

- name: Set permissions
  file: path=/home/deploy/gome/gome state=file owner=deploy group=deploy mode=0755

- name: Copy config.json
  copy: src=gome.json dest=/home/deploy/gome/config.json owner=root mode=0600
  notify: restart gome

- name: Copy upstart script
  template: src=upstart.conf.j2 dest=/etc/init/gome.conf owner=root mode=0644
  notify: restart gome

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{gome.host}}.conf
  notify: restart nginx

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/{{gome.host}}.conf path=/etc/nginx/sites-enabled/{{gome.host}}.conf state=link
  notify: restart nginx