---
- name: Add NR apt-key
  apt_key: url='https://download.newrelic.com/548C16BF.gpg' state=present

- name: Add NR repository
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: Install NR server monitor
  apt: pkg=newrelic-sysmond update_cache=yes state=latest cache_valid_time=86400

- name: Configure NR server monitor
  command: nrsysmond-config --set license_key={{ newrelic_key }}

- name: Start NR server monitor
  service: name=newrelic-sysmond state=started
