---
- name: Add jenkins apt-key
  apt_key: url='http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key' state=present

- name: Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: Remove invalid Jenkins src repository
  command: sed --in-place '/deb-src.*pkg.jenkins-ci/d' /etc/apt/sources.list

- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - git
    - curl
    - firefox
    - xvfb

- name: Install Jenkins
  apt: pkg=jenkins update_cache=yes state=installed cache_valid_time=86400
  register: jenkins_install

- name: Start jenkins
  service: name=jenkins state=started

- name: Create Jenkins CLI destination directory
  file: path=/var/lib/jenkins state=directory

- name: Create Jenkins .ssh directory
  file: path=/var/lib/jenkins/.ssh state=directory owner=jenkins group=jenkins

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/01-{{ jenkins_host }}.conf
  notify: restart nginx

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/01-{{ jenkins_host }}.conf path=/etc/nginx/sites-enabled/01-{{ jenkins_host }}.conf state=link
  notify: restart nginx

- name: Generate SSL cert
  command: "{{ le_cmd }} -d {{ jenkins_host }}"

