- name: Install OpenDKIM and related packages
  apt: pkg=$item state=installed
  with_items:
    - opendkim
    - opendkim-tools

- name: Create OpenDKIM config directory 
  file: state=directory path=/etc/opendkim group=opendkim owner=opendkim

- name: Create OpenDKIM key directories
  file: state=directory path=/etc/opendkim/keys/${item.name} group=opendkim owner=opendkim
  with_items:
    - ${mail_virtual_domains}

- name: Generate OpenDKIM keys
  command: opendkim-genkey -r -d ${item.name} -D /etc/opendkim/keys/${item.name}/ creates=/etc/opendkim/keys/${item.name}/default.private
  with_items:
    - ${mail_virtual_domains}

- name: Put OpenDKIM configuration files into place
  template: src=etc_opendkim_KeyTable.j2 dest=/etc/opendkim/KeyTable owner=opendkim group=opendkim
- template: src=etc_opendkim_SigningTable.j2 dest=/etc/opendkim/SigningTable owner=opendkim group=opendkim
- template: src=etc_opendkim_TrustedHosts.j2 dest=/etc/opendkim/TrustedHosts owner=opendkim group=opendkim
- copy: src=etc_opendkim.conf dest=/etc/opendkim.conf owner=opendkim group=opendkim

- name: Set OpenDKIM config directory permissions
  command: chmod -R go-rwx /etc/opendkim
- command: chown -R opendkim:opendkim /etc/opendkim
  notify:
    - restart opendkim
    - restart postfix