---
- name: Add logentries repo key
  apt_key: id=C43C79AD url=http://pgp.mit.edu:11371/pks/lookup?op=get&fingerprint=on&search=0xA5270289C43C79AD state=present

- name: Add logentries repo
  apt_repository: repo='deb http://rep.logentries.com/ {{ ansible_distribution_release }} main'

- name: Install logentries agent
  apt: name=logentries state=installed

- name: Register host if needed
  command: le register --account-key {{ logentries_key }} creates=/etc/le/config

- name: Install logentries daemon
  apt: name=logentries-daemon state=installed

- name: Follow logs
  command: le follow {{ item }}
  with_items: logentries_logs
  ignore_errors: yes

- name: Restart logentries
  service: name=logentries state=restarted