---
- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers regexp='^\%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL'

- name: Set locale
  command: "/usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}"

- name: Set /etc/localtime
  command: "/bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime"

- name: Set /etc/timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson python-pycurl python-passlib

- name: Install packages
  apt: name={{ item }} state=installed
  with_items:
    - ntp
    - build-essential
    - python-software-properties
    - software-properties-common
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - ssl-cert
    - git
    - htop
    - iftop
    - iotop
    - ruby1.9.3
    - screen
    - zsh
    - postfix
    - libmagickwand-dev
    - libreadline-dev
    - zlib1g-dev

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: NTP should be running
  action: service name=ntp state=running enabled=yes

- name: Remove packages
  apt: name={{ item }} state=absent
  with_items:
    - bind9
    - consolekit

- name: Copy resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf mode=0644

- include: security.yml tags=security
- include: ufw.yml tags=firewall
- include: logentries.yml tags=logentries
- include: tarsnap.yml tags=tarsnap
- include: ssl.yml tags=ssl,nginx
