---
- name: Set locale
  command: "/usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}"
  tags: main

- name: Set /etc/localtime
  command: "/bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime"
  tags: main

- name: Set /etc/timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata
  tags: main

- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson python-pycurl python-passlib
  tags:
    - main
    - nginx
    - ssl
    - jenkins

- name: Remove foreign keys
  file: path=/root/.ssh/authorized_keys2 state=absent
  tags: main

- name: SSHD config
  template: src=ssh.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify: restart ssh
  tags: main

- name: Install packages
  apt: name={{ item }} state=installed
  with_items:
    - ntp
    - build-essential
    - python-software-properties
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - ssl-cert
    - git
    - htop
    - zsh
    - postfix
    - graphicsmagick-libmagick-dev-compat
    - libmagickwand-dev
    - libreadline-dev
    - zlib1g-dev
  tags: 
    - main
    - nginx
    - ssl
    - jenkins

- name: NTP should be running
  action: service name=ntp state=running enabled=yes
  tags: main

- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers regexp='^\%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL'
  tags: main

- name: Remove packages
  apt: name={{ item }} state=absent
  with_items:
    - bind9
    - resolvconf
  tags: main

- name: Copy resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf mode=0644
  tags: main

- include: ufw.yml
- include: logentries.yml
# - include: tarsnap.yml
