---
- name: Install ansible dependencies
  raw: apt-get install -y python-apt python-simplejson
  tags: main

- name: Remove foreign keys
  file: path=/root/.ssh/authorized_keys state=absent
  tags: main

- name: SSHD config
  template: src=ssh.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify: restart ssh
  tags: main

- name: install packages
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - python-software-properties
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - ssl-cert
    - git
    - htop
    - zsh
  tags: 
    - main
    - nginx
    - ssl

- name: Allow users in the sudo group to run sudo without a password
  lineinfile: dest=/etc/sudoers regexp='^\%sudo' line='%sudo ALL=(ALL) NOPASSWD:ALL'
  tags: main

- include: ufw.yml
- include: logentries.yml
# - include: tarsnap.yml
