---
- name: Set locale
  command: "/usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}"

- name: Set /etc/localtime
  command: "/bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime"

- name: Set /etc/timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: Install ansible dependencies
  raw: apt-get install -y python-simplejson python-pycurl python-passlib python-psycopg2 python-pip

- name: Install pip
  raw: easy_install -U pip

- name: Install python modules
  pip: name={{ item }}
  with_items:
    - docker-py
    - virtualenv

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - ntp
    - build-essential
    - python-software-properties
    - software-properties-common
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - ssl-cert
    - git
    - htop
    - iftop
    - iotop
    - screen
    - zsh
    - postfix
    - libmagickwand-dev
    - libreadline-dev
    - zlib1g-dev
    - libxslt1-dev
    - libxml2-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - bison
    - libffi-dev

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: NTP should be running
  service: name=ntp state=running enabled=yes

- name: DNS config
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

# - name: Remove packages
#   apt: name={{ item }} state=absent
#   with_items:
#     - bind9
#     - consolekit

- name: Copy resolv to postfix chroot
  command: cp /etc/resolv.conf /var/spool/postfix/etc
  notify: restart postfix

- include: security.yml
  tags: security

- include: ufw.yml
  tags: firewall
