---
- name: Remove foreign keys
  file: path=/root/.ssh/authorized_keys state=absent
  tags: main

- name: SSHD config
  template: src=ssh.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify: restart ssh
  tags: main

- name: install packages
  apt: name={{ item }} state=installed
  with_items:
    - build-essential
    - python-software-properties
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
  tags: main

- include: ufw.yml
- include: logentries.yml
# - include: tarsnap.yml
