---
- name: Set locale
  command: "/usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}"

- name: Set /etc/localtime
  command: "/bin/cp /usr/share/zoneinfo/{{timezone}} /etc/localtime"

- name: Set /etc/timezone
  template: src=timezone.j2 dest=/etc/timezone
  notify: update tzdata

- name: Install ansible dependencies
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - python-simplejson
    - python-pycurl
    - python-passlib
    - python-psycopg2
    - python-pip
    - python-dev

- name: Install python modules
  pip: name={{ item }}
  with_items:
    - docker-py
    - virtualenv
    - glances

- name: Install packages
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - apt-transport-https
    - ntp
    - build-essential
    - python-software-properties
    - software-properties-common
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev
    - ssl-cert
    - git
    - htop
    - iftop
    - iptraf-ng
    - iotop
    - screen
    - zsh
    - postfix
    - libmagickwand-dev
    - libreadline-dev
    - zlib1g-dev
    - libxslt1-dev
    - libxml2-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - autoconf
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - bison
    - libffi-dev
    - p7zip-full
    - unrar

- name: Add multiverse repository
  apt_repository: repo="{{ item }}"
  register: multiverse_installed
  with_items:
   - "deb http://ubuntu.mirror.su.se/ubuntu/ {{ ansible_distribution_release }} multiverse"
   - "deb-src http://ubuntu.mirror.su.se/ubuntu/ {{ ansible_distribution_release }} multiverse"
   - "deb http://ubuntu.mirror.su.se/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"
   - "deb-src http://ubuntu.mirror.su.se/ubuntu/ {{ ansible_distribution_release }}-updates multiverse"

- name: Update apt cache
  apt: update_cache=true
  when: multiverse_installed | changed

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: NTP should be running
  service: name=ntp state=running enabled=yes

- name: Copy resolv to postfix chroot
  command: cp /etc/resolv.conf /var/spool/postfix/etc creates=/var/spool/postfix/etc/resolv.conf
  notify: restart postfix

- include: security.yml
  tags: security

- include: ufw.yml
  tags: firewall
