---
- name: Install dependencies for Tarsnap
  apt: pkg={{ item }} update_cache=yes state=latest cache_valid_time=86400
  with_items:
    - libssl-dev
    - zlib1g-dev
    - e2fslibs-dev

- name: Download Tarsnap source
  get_url: url=https://www.tarsnap.com/download/tarsnap-autoconf-${tarsnap.version}.tgz dest=/root/tarsnap-autoconf-${tarsnap.version}.tgz
  #sha256sum=6c9f6756bc43bc225b842f7e3a0ec7204e0cf606e10559d27704e1cc33098c9a

- name: Decompress Tarsnap source
  command: tar xzf /root/tarsnap-autoconf-${tarsnap.version}.tgz chdir=/root creates=/root/tarsnap-autoconf-${tarsnap.version}/COPYING

- name: Configure Tarsnap for local build
  command: ./configure chdir=/root/tarsnap-autoconf-${tarsnap.version} creates=/root/tarsnap-autoconf-${tarsnap.version}/Makefile

- name: Build and install Tarsnap
  command: make all install clean chdir=/root/tarsnap-autoconf-${tarsnap.version} creates=/usr/local/bin/tarsnap

- name: Copy Tarsnap key file into place
  copy: src=../../../secrets/tarsnap.key dest=/root/tarsnap.key owner=root group=root

- name: Create Tarsnap cache directory
  file: state=directory path=/usr/tarsnap-cache

# - name: Install nightly Tarsnap cronjob
#   cron: name="Tarsnap backup" hour="3" job="tarsnap --cachedir /usr/tarsnap-cache --keyfile /root/tarsnap.key -c -f backup-`date +\%Y\%m\%d` /home /root /decrypted-mail /var/www /var/log /var/lib/mysql > /dev/null"
