---
- name: firewall disable
  shell: yes | ufw disable

- name: firewall reset
  shell: yes | ufw reset

- name: firewall allow ssh
  command: ufw allow OpenSSH

- name: firewall allow ansible accelerated
  command: ufw allow 5099

- name: firewall deny all
  command: ufw default deny

- name:   firewall enable
  shell: yes | ufw enable