---
- name: Make sure mediawiki dir exists
  file: path=/usr/share/nginx/{{wiki_host}} state=directory owner=www-data group=www-data
  tags: mediawiki

- name: Check out version {{wiki_version}} of mediawiki
  sudo_user: www-data
  git: repo=https://git.wikimedia.org/git/mediawiki/core.git
       dest=/usr/share/nginx/{{wiki_host}}/w version={{wiki_version}}
  tags: mediawiki

- name: Copy php-fpm pool configuration
  template: src=php.conf.j2 dest=/etc/php5/fpm/pool.d/{{wiki_host}}.conf backup=yes
  notify: restart php-fpm
  tags: mediawiki

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{wiki_host}}.conf backup=yes
  notify: restart nginx
  tags: mediawiki

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/{{wiki_host}}.conf path=/etc/nginx/sites-enabled/{{wiki_host}}.conf state=link
  notify: restart nginx
  tags: mediawiki

- name: Create mediawiki db user
  sudo_user: postgres
  postgresql_user: user={{ wiki_dbuser }} password={{ item }} role_attr_flags=SUPERUSER
  with_password: ../../../secrets/{{ ansible_fqdn }}/mediawiki_db_password encrypt=sha256_crypt
  tags: mediawiki

- name: Create mediawiki database
  sudo_user: postgres
  postgresql_db: db={{ wiki_dbname }} owner={{ wiki_dbuser }}
  tags: mediawiki

- name: Run mediawiki installer
  sudo_user: www-data
  command: "php install.php --dbserver 127.0.0.1 --dbuser {{wiki_dbuser}} --dbpass {{item}}  --dbname {{wiki_dbname}} --dbtype postgres --installdbuser {{wiki_dbuser}} --installdbpass {{item}} --pass {{wiki_pass}} --scriptpath \"\" {{wiki_name}} {{wiki_login}}
    chdir=/usr/share/nginx/{{wiki_host}}/w/maintenance
    creates=/usr/share/nginx/{{wiki_host}}/w/LocalSettings.php"
  with_password: ../../../secrets/{{ ansible_fqdn }}/mediawiki_db_password encrypt=sha256_crypt
  tags: mediawiki

- name: Write mediawiki settings
  template: src=LocalSettings.php.j2 dest=/usr/share/nginx/{{wiki_host}}/w/LocalSettings.php backup=yes owner=www-data group=www-data mode=0644
  tags: mediawiki

- name: Download mediawiki extensions
  sudo_user: www-data
  command: git submodule update --init extensions/WikiEditor extensions/SyntaxHighlight_GeSHi extensions/CodeEditor extensions/Vector extensions/MobileFrontend
    chdir=/usr/share/nginx/{{wiki_host}}/w
  tags: mediawiki

- name: Copy logo
  copy: src=logo.png dest=/usr/share/nginx/{{wiki_host}}/w/logo.png owner=www-data group=www-data mode=0644
  tags: mediawiki