---
- name: Make sure mediawiki dir exists
  file: path=/var/www/mediawiki/w/ recurse=yes state=directory owner=www-data group=www-data mode=0755

- name: Download Mediawiki
  get_url: url=http://download.wikimedia.org/mediawiki/1.22/mediawiki-1.22.0rc3.tar.gz dest=/root/mediawiki.tar.gz

- name: Extract Mediawiki
  command: tar -xzf /root/mediawiki.tar.gz -C /var/www/mediawiki/w/ --strip-components 1

- name: Set permissions
  file: path=/var/www/mediawiki/w/ recurse=yes state=directory owner=www-data group=www-data mode=0755

- name: Copy php-fpm pool configuration
  template: src=php.conf.j2 dest=/etc/php5/fpm/pool.d/{{mediawiki.host}}.conf
  notify: restart php-fpm

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{mediawiki.host}}.conf
  notify: restart nginx

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/{{mediawiki.host}}.conf path=/etc/nginx/sites-enabled/{{mediawiki.host}}.conf state=link
  notify: restart nginx

- name: Write mediawiki settings
  template: src=LocalSettings.php.j2 dest=/var/www/mediawiki/w/LocalSettings.php owner=www-data group=www-data mode=0755

- name: Copy logo
  copy: src=logo.png dest=/var/www/mediawiki/w/logo.png owner=www-data group=www-data mode=0644

- name: Create db
  postgresql_db: name=mediawiki login_host=localhost login_password=docker login_user=docker

- name: Create user
  postgresql_user: db=mediawiki name=mediawiki password=mediawiki priv=ALL login_host=localhost login_password=docker login_user=docker