---
- name: Make sure mediawiki dir exists
  file: path=/usr/share/nginx/{{wiki_host}}/w state=directory owner=www-data group=www-data

- name: Check out version {{wiki_version}} of mediawiki
  sudo_user: www-data
  git: repo=https://git.wikimedia.org/git/mediawiki/core.git
       dest=/usr/share/nginx/{{wiki_host}}/w version={{wiki_version}}

- name: Copy php-fpm pool configuration
  template: src=php.conf.j2 dest=/etc/php5/fpm/pool.d/{{wiki_host}}.conf backup=yes
  notify: restart php-fpm

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{wiki_host}}.conf backup=yes
  notify: restart nginx

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/{{wiki_host}}.conf path=/etc/nginx/sites-enabled/{{wiki_host}}.conf state=link
  notify: restart nginx

- name: Write mediawiki settings
  template: src=LocalSettings.php.j2 dest=/usr/share/nginx/{{wiki_host}}/w/LocalSettings.php backup=yes owner=www-data group=www-data mode=0644

- name: Download mediawiki extensions
  sudo_user: www-data
  command: git submodule update --init extensions/WikiEditor extensions/SyntaxHighlight_GeSHi extensions/CodeEditor extensions/Vector extensions/MobileFrontend
    chdir=/usr/share/nginx/{{wiki_host}}/w

- name: Copy logo
  copy: src=logo.png dest=/usr/share/nginx/{{wiki_host}}/w/logo.png owner=www-data group=www-data mode=0644
