---
tarsnap:
  version: 1.0.35
  hash: 6c9f6756bc43bc225b842f7e3a0ec7204e0cf606e10559d27704e1cc33098c9a

ssl:
  crt: /etc/ssl/certs/wildcard_public_cert.crt
  key: /etc/ssl/private/wildcard_private.key
  pem: /etc/ssl/certs/wildcard_ca.pem
