---
- name: get Hama src
  get_url: url={{ plex_hama_src }} dest=/tmp/plex_hama_src.zip

- name: unpack Hama src
  command: 7z x -o{{ plex_lib | quote }} /tmp/plex_hama_src.zip
  args:
    creates: "{{ plex_lib }}/HAMA\ +\ Absolute\ Series\ Scanner/Plug-ins/Hama.bundle/Contents/Code/__init__.py"

- name: set Hama src mode
  file: path="{{ plex_lib }}/HAMA + Absolute Series Scanner/" mode=0755 owner=plex group=plex state=directory recurse=yes

- name: copy Hama src
  shell: cp -r /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/HAMA\ +\ Absolute\ Series\ Scanner/* {{ plex_lib | quote }}
  notify: restart plexmediaserver

- name: get Hama bundle
  get_url: url={{ plex_hama_bundle }} dest="{{ plex_lib }}/Plug-ins/Hama.bundle/Contents/Code/__init__.py" mode=0644 owner=plex group=plex force=yes
  notify: restart plexmediaserver

- name: get scanner
  get_url: url={{ plex_hama_scanner }} dest="{{ plex_lib }}/Scanners/Series/Absolute Series Scanner.py" mode=0644 owner=plex group=plex force=yes
  notify: restart plexmediaserver
