---
- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    - avahi-daemon
    - avahi-utils

- name: download plex media server
  get_url: url={{ plex_download_url }} dest=/tmp/{{ plex_deb_package }}

- name: install plex media server
  apt: deb=/tmp/{{ plex_deb_package }} state=installed
  notify: restart plexmediaserver

- name: create media user
  user: name=media createhome=no system=yes

- name: create directories
  file: path={{ item.path }} owner=media group=media mode=2775 state=directory
  with_items:
    - path: /var/media
    - path: /var/media/tv
    - path: /var/media/movies
    - path: /var/media/download

- name: add plex user to media
  user: name=plex groups=plex,media append=yes

- name: default config file
  template: src=default.j2 dest=/etc/default/plexmediaserver
  notify: restart plexmediaserver

- name: upgrade plex media server
  apt: name=plexmediaserver update_cache=yes state=latest cache_valid_time=86400
  notify: restart plexmediaserver

- name: update configuration
  template: src=init.j2 dest=/etc/init/plexmediaserver.conf mode=644
  notify: restart plexmediaserver

- name: copy plex ufw conf
  template: src=ufw.j2 dest=/etc/ufw/applications.d/plex owner=root group=root mode=0644

- name: firewall allow plex
  command: ufw allow plex
