---
- name: restart postfix
  service: name=postfix state=restarted

- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart solr
  service: name=tomcat6 state=restarted