---
- name: Add repo key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add repo
  apt_repository: repo='deb https://repos.influxdata.com/debian jessie stable'

- name: Install packages
  apt: name=telegraf update_cache=yes state=installed cache_valid_time=86400
  notify: restart telegraf

- name: enable service
  service: name=telegraf state=started enabled=yes
