---
- name: Create database user for ownCloud
  mysql_user: user={{ owncloud_mysql_username }} password={{ item }} state=present priv="owncloud.*:ALL"
  with_password: ../../../secrets/{{ ansible_fqdn }}/owncloud_db_password encrypt=sha256_crypt

- name: Create database for ownCloud
  mysql_db: name={{ owncloud_mysql_database }} state=present

- name: Ensure repository key for ownCloud is in place
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_13.04/Release.key state=present

- name: Add ownCloud OpenSuSE repository
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_13.04/ /'

- name: Install ownCloud from OpenSuSE repository
  apt: pkg=owncloud update_cache=yes

- name: Copy php-fpm pool configuration
  template: src=php.conf.j2 dest=/etc/php5/fpm/pool.d/{{owncloud_domain}}.conf backup=yes
  notify: restart php-fpm

- name: Copy nginx site configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{owncloud_domain}}.conf backup=yes
  notify: restart nginx

- name: Link nginx site configuration
  file: src=/etc/nginx/sites-available/{{owncloud_domain}}.conf path=/etc/nginx/sites-enabled/{{owncloud_domain}}.conf state=link
  notify: restart nginx

- name: Install ownCloud cronjob
  cron: name="ownCloud" user="www-data" minute="*/5" job="php -f /var/www/owncloud/cron.php > /dev/null"